### ISSUE TITLE
Create a GCC toolchain to move away from IAR Workbench. 

### ISSUE THREAD

**Issue by JeanRintoul** [OpenEIT/EIT_Firmware#1]
OpenOCD is another Open Toolchain Option. Whichever toolchain it moves to the version of compilers, and install procedure should also be documented in a readme. 

Here is a thread on the ADuCM350 forum that details current status. 
https://ez.analog.com/thread/72704

**Comment by dl1chb** [comment]
A Makefile for compiling it using the gcc would be nice. I am trying to build one, but its hard by just looking at the bare code without a dependency list of used libs and so on.

**Comment by JeanRintoul** [comment]
There is a separate thread going on to create an MBED GCC toolchain implementation on this - will try to get you in contact with person working on it. Also, check out: https://github.com/LabLabUG/ADuCM350_SVD

**Comment by dl1chb** [comment]
Okay, thanks! I try to get it working.

**Comment by JeanRintoul** [comment]
Hi all, There is now a gcc port using eclipse as the editor by dioptre in the gcc-toolchain branch of this repository that has Analog Devices blessings. To get the compiler working with the ADuCM350 SDK use this: https://github.com/dioptre/ADuCM350

Other resources for this project include https://github.com/LabLabUG/ADuCM350_SVD

https://github.com/clevertrack1 is also working on an mbed version here: https://github.com/clevertrack1/gnuADuCM350
